# Generated by Django 3.1.4 on 2020-12-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('adress', models.CharField(max_length=100)),
                ('store_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
