# Generated by Django 3.1.4 on 2020-12-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappi_app', '0003_auto_20201227_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
