# Generated by Django 3.1.4 on 2020-12-27 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mappi_app', '0004_auto_20201227_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_sentence', models.CharField(max_length=140)),
                ('review_score', models.IntegerField(max_length=6)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mappi_app.store')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mappi_app.user')),
            ],
        ),
    ]
