# Generated by Django 3.1.4 on 2020-12-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappi_app', '0005_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_score',
            field=models.IntegerField(),
        ),
    ]
