# Generated by Django 3.1.4 on 2020-12-27 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappi_app', '0006_auto_20201227_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='review',
            name='review_score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
