# Generated by Django 3.1.4 on 2020-12-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappi_app', '0008_auto_20201227_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='want_flag',
            field=models.BooleanField(default=False),
        ),
    ]
