# Generated by Django 3.1.4 on 2021-01-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappi_app', '0010_auto_20201231_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
